- src/Phake.php
@internal should not be used for parameters. This also changes
`partialMock()` to actually define its parameters rather than solely
using `func_get_args()`.
Fixes #161
> Use @param PhpDoc for partialMock parameters

- src/Phake/ClassGenerator/MockClass.php
- tests/Phake/ClassGenerator/MockClassTest.php
- tests/PhakeTest/MockedFinalConstructedClass.php
During my test, I wanted to mock a class with a final constructor like this one https://github.com/doctrine/annotations/blob/master/lib/Doctrine/Common/Annotations/Annotation.php which has a final constructor.
I have added a test for this case.
What are your thoughts about this issue?
Regards
> Prevent constructor override when constructor is final

- src/Phake/ClassGenerator/MockClass.php
- tests/Phake/ClassGenerator/MockClassTest.php
- tests/PhakeTest/AbstractImplementConstructorInterface.php
- tests/PhakeTest/ImplementConstructorInterface.php
Hi,
I also had this issue with a class which extend an abstract class which implements an interface and the constructor is defined in the interface and implemented only in the base class.
I noticed that getConstructor() method always returns null on the interfaces, therefore I have added a little test.
What are your thoughts about this issue?
Regards,
> prevent constructor override when class extend abstract and implement interface with constructor

- docs/answers.rst
- src/Phake/Proxies/AnswerBinderProxy.php
- tests/Phake/Matchers/ReferenceSetterTest.php
- tests/Phake/Proxies/AnswerBinderProxyTest.php
- tests/PhakeTest.php
Left the other method in so as not to break backwards compatibility.
> Replace thenGetReturnByLambda with thenReturnCallback and deprecate

- docs/method-parameter-matchers.rst
fooWithArgument() was referenced where deal() should have been referenced, likely due to copy/paste error
> Fixed fooWithArgument() references in Method Parameter Matchers

- docs/method-parameter-matchers.rst
The Hamcrest link is just to the README because there doesn't appear to be more specific documentation available.
> Added links to PHPUnit constraints and Hamcrest matchers

- src/Phake/ClassGenerator/MockClass.php
- tests/Phake/ClassGenerator/MockClassTest.php
Split in to two methods. Use correct way to create new object without constructor. Use less reflection.
We encountered a bug where PHP 5.6.10 would crash when using the @ operator on the unserialize() function. Removing the @ operator fixed the issue, so I created a PR in which the @ operator is no longer required. Gives also clearer code, and instanciates far fewer objects. E.g. in the master branch the $mockObject would be instanciated and overwritten a few times.
> Clean up method that creates mocks.

- .travis.yml
Since phpunit 4.8 still supports php 5.3 I don't see a compelling reason to continue testing 3.* or earlier 4.*.
> Adjusting travis build. 

- .travis.yml
- src/Phake.php
- src/Phake/ClassGenerator/MockClass.php
- src/Phake/Stubber/Answers/SmartDefaultAnswer.php
- tests/Phake/ClassGenerator/MockClassTest.php
- tests/Phake/Stubber/Answers/SmartDefaultAnswerTest.php
- tests/PhakeTest/ScalarTypes.php
Return types are particularly tricky as now PHP does not allow returning null for hinted return types. This results in a behavioral change for Phake. Now, by default, the default value for each given return type will be the default answer. The defaults are achieved by essentially the "empty" value for each built-in type: 0, 0.0, '', false, array(). A hoop function is the default value for a callable, and if the return type is another class, a mock of that class will be returned.
> Adding support for scalar type hints and return types.

- docs/mocks.rst
- src/Phake/ClassGenerator/MockClass.php
- src/Phake/Facade.php
- tests/Phake/ClassGenerator/MockClassTest.php
- tests/Phake/FacadeTest.php
- tests/PhakeTest.php
- tests/PhakeTest/MockedChildInterface.php
- tests/PhakeTest/MockedInterface2.php
You can now specify an array of classes and interfaces to Phake::mock() or Phake::partialMock(). Fixes #185
> Allow mocking multiple interfaces at once.

- src/Phake/Matchers/IMethodMatcher.php
- src/Phake/Matchers/MethodMatcher.php
- src/Phake/Stubber/StubMapper.php
- tests/Phake/Stubber/StubMapperTest.php
This change speeds up performance of matching stubs by using
an associative array for storing the matchers for a mock object.
Part of this change adds a getter method to IMethodMatcher,
which means it will force any class that implements this
interface to implement getMethod().  This makes this change a breaking
change, so it should be handled accordingly.
This change adde
> Use associative array for matching

- docs/answers.rst
The stubbed method doesn't take a parameter, but answer callback does, which results in the latter not being called.
> Fix Answer Callbacks code example

- src/Phake/PHPUnit/VerifierResultConstraint.php
Ran into an issue with this test: https://github.com/phergie/phergie-irc-plugin-react-url/blob/b6525364c269050e2f98d6da3394da48766d7d0d/tests/DefaultUrlHandlerTest.php#L120
```
PHPUnit 2.0.1-13-g4a4f0f5 by Sebastian Bergmann.
Configuration read from /Users/halo/PhpstormProjects/phergie-irc-plugin-react-url/phpunit.xml
The Xdebug extension is not loaded. No code coverage will be generated.
.......E...................................................
Time: 0 seconds, Memory: 6.00Mb
There was 1 error:
1) Phergie\Tests\Irc\Plugin\React\Url\DefaultUrlHandlerTest::testHandle
Declaration of Phake_PHPUnit_VerifierResultConstraint::evaluate($other) should be compatible with PHPUnit_Framework_Constraint::evaluate($other, $description = '', $returnResult = false) …
```
> update evaluate signature in Phake_PHPUnit_VerifierResultConstraint

- .travis.yml
- docs/mocks.rst
- src/Phake/ClassGenerator/MockClass.php
- src/Phake/Stubber/Answers/ParentDelegate.php
- src/Phake/Stubber/Answers/ParentDelegateCallback.php
- tests/Phake/ClassGenerator/MockClassTest.php
- tests/Phake/Proxies/VisibilityProxyTest.php
- tests/Phake/Stubber/Answers/ParentDelegateTest.php
- tests/PhakeTest.php
Fixes #212 by revamping a little bit how the callback from thenCallParent() works. This needs some cleanup but I have other code that is focused on reworking all of the answers a bit more and the cleanup makes more sense to happen there.
> Should resolve the lack of private support (essentially) in makeVisible()

- src/Phake/Proxies/AnswerBinderProxy.php
- src/Phake/Stubber/Answers/InvalidAnswerException.php
- src/Phake/Stubber/Answers/SelfAnswer.php
- tests/Phake/Proxies/AnswerBinderProxyTest.php
- tests/Phake/Stubber/Answers/SelfAnswerTest.php
- tests/PhakeTest.php
Fixes #215 
This assists in testing fluent interfaces:
Phake::when($mock)->foo->thenReturnSelf();
$mock->foo()->foo();
Phake::mock('MyFluentApi', Phake::ifUnstubbed()->thenReturnSelf());
> Adding the ability to return the mock object back.

- src/Phake/ClassGenerator/MockClass.php
- tests/Phake/BuiltInExtensionsTest.php
This fixes #214
There are some issues with how some extensions work in terms of inheritance where you can never exactly match the method signature of what you are extending. In this case a strict error is thrown which often gets translated into a failed test in PHPUnit. I have added a whitelist of classes that will bypass strict error checking. Until a better solution is provided upstream:
https://github.com/php-memcached-dev/php-memcached/issues/126
> Added ability to mock "unsafe classes"

- src/Phake/Matchers/Factory.php
- src/Phake/Matchers/PHPUnit6ConstraintAdapter.php
Unfortunately Phake does not work with PHPUnit 6 because classnames are changed to use namespaces. 
This pull requests solves that Phake accepts the PHPUnit 6 Constraints in the verify step.
> Make matchers work with PHPUnit 6

- docs/mocking-statics.rst
This example in the documentation had two small errors.
- Instead of using `Phake::verifyStatic()`, it used `Phake::verify()`.
- `Phake::anyParameter()` should be `Phake::anyParameters()`.
> Fix "Mocking Static Methods" documentation example

- src/Phake.php
- tests/PhakeTest.php
- tests/PhakeTest/ClassWithStaticMethod.php
- tests/PhakeTest/StaticMethod.php
`Phake::resetStatic()` clears the internal states but did not return the original class name, this commit will address this issue backed by a followup test 
@mlively thoughts ?
> Fix Phake::resetStatic() post calls

- src/Phake.php
- src/Phake/Matchers/Factory.php
We've seen that about 5% of our test run is spent in creating new `\SebastianBergmann\Comparator\Factory`'s. 
We have about 3,000 tests with Phake. 
I still need to fix the white space and style, but I wanted to check this PR with you @mlively.
> Keep cached version of matcher factory and comparator factory around

- src/Phake/Proxies/AnswerCollectionProxy.php
- src/Phake/Proxies/AnswerProxyInterface.php
- tests/PhakeTest.php
Basically dropped all of the answers into an interface and implemented it on the answercollection and answerbinder proxies.
> Fixes #239 - thenDoNothing() missing on Phake_Proxies_AnswerCollectionProxy

- src/Phake/ClassGenerator/MockClass.php
- tests/PhakeTest/ScalarTypes.php
This PR fixes that you currently cannot mock a class that uses `self` as return type hint (issue #226).
> Support self return type in mocked class, fixes #226

- src/Phake.php
- src/Phake/Matchers/Factory.php
- tests/Phake/CallRecorder/VerifierTest.php
- tests/Phake/Matchers/EqualsMatcherTest.php
- tests/Phake/Proxies/CallVerifierProxyTest.php
- tests/Phake/Proxies/VerifierProxyTest.php
Saves lots of object initialization but more importantly allows us to register customer Comparators.
> Use the global Comparator factory. 

- docs/mocks.rst
One of the example proposed had wrong parameters on assertEquals()
> Fix assertEquals() parameters

- src/Phake.php
Will now check the newer version of PHPUnit first before moving onto the older versions. When working with Codeception, they alias the underscore version of the class, and so the wrong version is returned.
> Check newer PHPUnit versions first

- .travis.yml
- src/Phake/Annotation/Reader.php
- tests/Phake/Annotation/MockInitializerParentTestCase.php
- tests/Phake/Annotation/MockInitializerSubclassTest.php
- tests/Phake/Annotation/ReaderTest.php
- tests/Phake/ClassGenerator/MockClassTest.php
This fixes having mock annotations that use imports on a parent test not finding the class. Instead of just getting property names, it now returns the `ReflectionProperty` so that we can get more information from it (such as the declaring class). We also then don't need to create another `ReflectionProperty` to modify it.
Fixes: #273
> Use ReflectionProperty to fix parent mock annotations

- src/Phake/CallRecorder/Recorder.php
Phake's "resetStatic" didn't reset the unverified calls list.
This lead to a memory leak when running multiple tests
> Fix memory leak

- src/Phake/Facade.php
- src/Phake/Mock/Info.php
- tests/Phake/ClassGenerator/MockClassTest.php
`uniquid()` is not without its flaws - but most importantly it is rather slow. 
This PR replaces uniqid with `bin2hex(random_bytes(7))` which gives a comparable result.
> Performance: replace uniqid with random_bytes

- src/Phake/Annotation/MockInitializer.php
- tests/Phake/Annotation/MockInitializerClassWithTestNamespaceTest.php
Fixes #275, if the class is not found in the list of `use` statements, it will check if the class exists under the defined namespace. If so, it will prepend the NS onto the mocked class so it can be imported properly.
> Prepend test namespace for mocked classes defined under that namespace

- src/Phake/ClassGenerator/MockClass.php
- src/Phake/Stubber/Answers/SmartDefaultAnswer.php
PHPUnit throws deprecation errors when Phake uses this method in PHP 7.4
ErrorException: Function ReflectionType::__toString() is deprecated
This patch replaces the instances of (string)$returnType with $returnType->getName(); allowing Phake to work on PHP 7.4 without deprecation warnings/errors.
Resolves issue #279
> ReflectionType::__toString() is deprecated in PHP 7.4

- docs/method-stubbing.rst
I believe the docs are wrong
```
Error: Call to undefined method Phake::staticReset()
```
> Rename staticReset -> resetStatic

- src/Phake/Annotation/IReader.php
- src/Phake/Annotation/LegacyReader.php
- src/Phake/Annotation/MockInitializer.php
- src/Phake/Annotation/NativeReader.php
- tests/Phake/Annotation/LegacyReaderTest.php
- tests/Phake/Annotation/MockInitializerTypedPropertiesTest.php
- tests/Phake/Annotation/NativeReaderTest.php
- tests/bootstrap.php
Example
```php
class Foo {
/** @Mock */
private stdClass $foo;
}
```
This commit introduce a new `Phake\Annotation\IReader` interface.
There are two implementations of this class :
`Phake\Annotation\LegacyReader` (default for php7)
This is the Phake 3.X way to do with the @Mock and @var annotations in the comments.
`Phake\Annotation\NativeReader` (default for php8)
This is the new way to do it. You need to add a `Phake\Mock` native attribute to your property.
```php
class Foo {
#[Phake\Mock]
private stdClass $mock;
#[Phake\Mock(stdClass::class)]
private $mock1;
#[Phake\Mock(class: stdClass::class)]
private $mock2
}
```
If you're using PHP8 but still want to load the old way you can use
```
Phake\Annotation\MockInitializer::setDefaultReader(
new Phake\Annotation\LegacyReader()
);
```
> Add support for native annotations

- src/Phake/ClassGenerator/MockClass.php
Like I said in #301 this is only a temporary fix to avoid the deprecation error. The real work to do to prepare PHP 9.0 correctly is to infer the good return type, which is not OK with interfaces currently.
> Temporary fix for #301

- src/Phake/ClassGenerator/MockClass.php
- src/Phake/Exception/NeverReturnMethodCalledException.php
- src/Phake/Stubber/Answers/SmartDefaultAnswer.php
- tests/Phake/ClassGenerator/MockClassTest.php
- tests/Phake/Stubber/Answers/SmartDefaultAnswerTest.php
- tests/PhakeTest.php
- tests/PhakeTest/IntersectionTypes.php
- tests/PhakeTest/NeverReturn.php
- tests/PhakeTest/SerializableClass.php
It's now possible to mock class that use pure intersection types :
```
interface Foo {
public function bar(ArrayAccess & Countable $baz): ArrayAccess & Countable;
}
$mock = Phake::mock(Foo::class);
$result = $mock->bar(new ArrayObject);
var_dump($result instanceof Countable); // true
var_dump($result instanceof ArrayAccess); // true
```
And also never return type
```
class Foo {
public function foo(): never
{
}
}
try {
$mock = Phake::mock(Foo::class);
$mock->foo();
} catch (\Exception $e) {
var_dump(get_class($e)); // Phake\Exception\NeverReturnMethodCalledException
}
```
> Add support for PHP8.1 pure intersection types and never return type

- src/Phake.php
When using Phake to create a mock, the mock object returned is declared by the PHPDoc as `mixed`, which causes issue in static-analysis tools like PHPStan or Psalm when using the mock object.
What is hard here is that the mock object is a `\Phake\IMock` object but also shares its definition with the class/interface(s) we are mocking.
After[ a little help asked on PHPStan project](https://phpstan.org/r/f06ef7e7-6d54-4734-b45e-a05bd50adc09), I finally came to a solution I tested on my side which works.
With this new type-hints, neither PHPStan nor Psalm complains anymore.
Would it be OK this way?
Thanks a lot.
> Provide a better type-hint for mock and partial mock objects

- CHANGELOG.md
- src/Phake.php
- src/Phake/ClassGenerator/MockClass.php
- src/Phake/Facade.php
- src/Phake/Mock/InfoRegistry.php
- tests/Phake/ClassGenerator/MockClassTest.php
- tests/Phake/FacadeTest.php
- tests/Phake/Mock/InfoRegistryTest.php
- tests/Phake/Proxies/CallStubberProxyTest.php
- tests/PhakeTest.php
This is an experimental branch to move all mocking storage (`Mock\Info` objects) out of the mock object. This will make it possible to mock `readonly` objects.
> WIP - Store mock info outside of the object

- src/Phake/Mock.php
Phake uses the `Phake\Mock` marker for attributes to mock a class, but this attribute doesn't exist, which causes warnings in PHPStorm.
This PR adds this attribute as a concrete class, to remove warnings in the IDE.
> Add Phake\Mock attribute class

- .github/workflows/tests.yml
- composer.json
- src/Phake.php
- src/Phake/Client/PHPUnit12.php
- tests/Phake/Client/PHPUnitXTest.php
This PR is the same as #326 but from base branch 4.5 in order to stay in major version 4.
> Add compatibility with PHPUnit12 for PHP 8.3 (from v4.5).

- composer.json
This is a bugfix because otherwise, you wouldn't be allowed to require sebastian/comparator with 7.x, only 7.0.0.
Sebastian Bergmann released a patch as 7.0.1 for PHPUnit 12.0.7 last friday, and Phake enters in conflict because of this typo. 
Otherwise, maybe you should consider #326 :wink:
> Missing allowance of sebastian/comparator 7.x
